# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GetNSIData
                                 A QGIS plugin
 This plugin downloads data from the U.S. National Structures Inventory for a specified state or region.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-12-21
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sebastian Rowan
        email                : sebastian.rowan@unh.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QUrl
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.PyQt.QtNetwork import QNetworkRequest, QNetworkReply,  QNetworkAccessManager
from qgis.core import QgsProject, Qgis
import os
import os.path
import tempfile
import json

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .get_nsi_data_dialog import GetNSIDataDialog, GetStateNSIDataDialog, GetBboxNSIDataDialog
from .census_objects import State, County, Tract



class GetNSIData:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GetNSIData_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)
        
        self.dir = tempfile.gettempdir() 
        self.states = self.get_states()
        self.fips = None
        
        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Get NSI Data')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GetNSIData', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/get_nsi_data/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Get NSI Data by State'),
            callback=self.runState,
            parent=self.iface.mainWindow())

        self.add_action(
            icon_path,
            text=self.tr(u'Get NSI Data by FIPS'),
            callback=self.runFips,
            parent=self.iface.mainWindow())
            
        self.add_action(
            icon_path,
            text=self.tr(u'Get NSI Data by Bounding Box'),
            callback=self.runBbox,
            parent=self.iface.mainWindow())
            
        # will be set False in run()
        self.first_start = True

    
    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Get NSI Data'),
                action)
            self.iface.removeToolBarIcon(action)
    
    def updateDir(self):
        self.dir = self.dlgState.stateSaveLine.text()
    
    def get_states(self):
        
        # Read in states, counties, and tracts with their fips codes
        json_file_path = os.path.join(
            self.plugin_dir,
            "tracts_nested.json"
            ).replace('\\','/') # just putting the file name in the open call causes error. Need better solution.
        f = open(json_file_path)
        data = json.loads(f.read())
        
        states = {}
        for i in data:
            state_name = i['state_name']
            state_fips = i['state_fips']
            state_counties = {}
            for j in i['counties']:
                county_name = j['county_name']
                county_fips = j['county_fips']
                county_tracts = {"Use County FIPS": Tract("Use County Fips", county_fips)}
                for k in j['tracts']:
                    tract_name = k['tract_name']
                    tract_fips = k['tract_fips']
                    tract_k = Tract(tract_name, tract_fips)
                    county_tracts[tract_name] = tract_k
                county_j = County(county_name, county_fips, county_tracts)
                state_counties[county_name] = county_j
            state_i = State(state_name, state_fips, state_counties)
            states[state_name] = state_i
        return(states)    
    
    def selectStateOutputFolder(self):
        folderName = QFileDialog.getExistingDirectory(self.dlgState, "Select output folder")
        self.dlgState.stateSaveLine.setText(folderName)
        self.updateDir()
            
    def runState(self):
        """Run method that performs all the real work"""
        self.dlgState = GetStateNSIDataDialog(self.iface)
        self.dir = tempfile.gettempdir()
        self.dlgState.stateFolderButton.clicked.connect(self.selectStateOutputFolder)
        self.dlgState.stateSaveLine.textChanged.connect(self.updateDir)
        
        
        # Clear the contents of the state comboBox from previous runs
        self.dlgState.comboBoxState.clear()
        # Populate the comboBox with state names
        self.dlgState.comboBoxState.addItems([state for state in self.states.keys()])
        

        # show the dialog
        self.dlgState.show()
        # Run the dialog event loop
        result = self.dlgState.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            fips = self.states[self.dlgState.comboBoxState.currentText()].fips[0]
            print(f"fips: {fips}")
            dest = self.dir
            # self.getStateData(fips, dest)
            self.dlgState.downloader.get_state_data(fips, dest)
            
    
    def runFips(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        self.dlgFips = GetNSIDataDialog(self.iface)
        self.dir = tempfile.gettempdir()
        self.dlgFips.fipsFolderButton.clicked.connect(self.fips_select_output_folder)
        self.dlgFips.fipsSaveLine.textChanged.connect(self.fips_update_dir)
        self.dlgFips.comboBoxState.addItems([state for state in self.states.keys()])
        self.fips_update_combo_box_county()
        self.fips_update_combo_box_tract()
        self.fips_update_label()
        
        self.dlgFips.comboBoxState.currentTextChanged.connect(self.fips_update_combo_box_county)
        self.dlgFips.comboBoxCounty.currentTextChanged.connect(self.fips_update_combo_box_tract)
        self.dlgFips.comboBoxTract.currentTextChanged.connect(self.fips_update_label)
        
        # show the dialog
        self.dlgFips.show()
        # Run the dialog event loop
        result = self.dlgFips.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            self.dlgFips.downloader.get_structs_fips(self.fips, self.dir)
            pass
    
    def runBbox(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        self.dlgBbox = GetBboxNSIDataDialog(self.iface)
        self.dir = tempfile.gettempdir()
        
        # show the dialog
        self.dlgBbox.show()
        # Run the dialog event loop
        result = self.dlgBbox.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
    
    def fips_update_combo_box_county(self):
        self.dlgFips.comboBoxCounty.clear()
        state = self.dlgFips.comboBoxState.currentText()
        counties = self.states[state].counties.keys()
        self.dlgFips.comboBoxCounty.addItems([county for county in counties])
        
    def fips_update_combo_box_tract(self):
        state = self.dlgFips.comboBoxState.currentText()
        county = self.dlgFips.comboBoxCounty.currentText()
        self.dlgFips.comboBoxTract.clear()
        counties = self.states.get(state).counties
        county_get = counties.get(county)
        if county_get is None:
            # This function also gets called when the county box is cleared when a new state is selected.
            # This would an AttributeError when trying to get the tracts
            pass
        else:
            tracts = county_get.tracts.keys()
            self.dlgFips.comboBoxTract.addItems(tracts)
            
    def fips_update_label(self):
        state = self.dlgFips.comboBoxState.currentText()
        county = self.dlgFips.comboBoxCounty.currentText()
        tract = self.dlgFips.comboBoxTract.currentText()
        county_get = self.states.get(state).counties.get(county)
        if county_get is None:
            pass
        else:
            tract_get = county_get.tracts.get(tract)
            if tract_get is None:
                pass
            else:
                self.dlgFips.labelFips.setText(tract_get.fips)
                self.fips = tract_get.fips
                
    def fips_select_output_folder(self):
        folder_name = QFileDialog.getExistingDirectory(self.dlgFips, "Select output folder")
        self.dlgFips.fipsSaveLine.setText(folder_name)
        self.fips_update_dir()
        
    def fips_update_dir(self):
        self.dir = self.dlgFips.fipsSaveLine.text()
        
        
