# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GetNSIDataDialog
                                 A QGIS plugin
 This plugin downloads data from the U.S. National Structures Inventory for a specified state or region.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-21
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Sebastian Rowan
        email                : sebastian.rowan@unh.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from .nsiDownload import StateDownload, APIDownload

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'get_nsi_data_dialog_base.ui'))

class GetNSIDataDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(cls, iface, parent=None):
        """Constructor."""
        super(GetNSIDataDialog, cls).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After cls.setupUi() you can access any designer object by doing
        # cls.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        cls.setupUi(cls)
        cls.iface = iface
        cls.downloader = APIDownload(cls, cls.iface)
    

FORM_CLASS_STATE, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'get_state_nsi_data_dialog_base.ui'))

class GetStateNSIDataDialog(QtWidgets.QDialog, FORM_CLASS_STATE):
    def __init__(cls, iface, parent=None):
        """Constructor."""
        super(GetStateNSIDataDialog, cls).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After cls.setupUi() you can access any designer object by doing
        # cls.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        cls.setupUi(cls)
        cls.iface = iface
        cls.downloader = StateDownload(cls, cls.iface)